package cmd_test

import (
	"github.com/bwmarrin/discordgo"
	"github.com/tristan-club/kit/log"
	"github.com/tristan-club/wizard/handler/discordhandler/dcontext"
	"github.com/tristan-club/wizard/handler/discordhandler/handler"
	"time"
)

var Handler = &handler.DiscordCmdHandler{
	ApplicationCommand: &discordgo.ApplicationCommand{
		ApplicationID: "",
		Options:       nil,
		Version:       "1",
	},
	Handler: testHandler,
}

var content = `ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMNABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMNABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMNABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMNABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMNABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMNABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN
ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN ABCDEFGHIJKLMN

`
var isProcessed bool

// 编辑机器人头像的示例
func updateBotIconExample(ctx *dcontext.Context) error {
	u, err := ctx.Session.UserUpdate("wizard-local-my", "data:image/png;base64,iVBORw0KGgoAAA\nANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4\n//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU\n5ErkJggg==")
	if err != nil {
		log.Error().Fields(map[string]interface{}{"action": "error", "error": err.Error()}).Send()
	} else {
		log.Info().Fields(map[string]interface{}{"action": "u", "u": u}).Send()
	}
	return nil
}

func testHandler(ctx *dcontext.Context) error {

	err := ctx.Session.InteractionRespond(ctx.IC.Interaction,
		&discordgo.InteractionResponse{
			Type: discordgo.InteractionResponseChannelMessageWithSource,
			Data: &discordgo.InteractionResponseData{
				TTS:             false,
				Content:         "123456",
				Components:      nil,
				Embeds:          nil,
				AllowedMentions: nil,
				Files:           nil,
				Flags:           discordgo.MessageFlagsEphemeral,
				Choices:         nil,
				CustomID:        "",
				Title:           "",
			},
		})
	if err != nil {
		log.Error().Fields(map[string]interface{}{"action": "get user error", "error": err.Error()}).Send()
	}
	return nil

	if !isProcessed {
		go func() {
			isProcessed = true
			var j int
			for {

				for i := 0; i < 51; i++ {
					i := i
					go func() {

						_, err := ctx.Session.User(ctx.GetFromId())
						if err != nil {
							log.Error().Fields(map[string]interface{}{"action": "get user error", "error": err.Error()}).Send()
						}

						log.Info().Msgf("round %d route %d second %v", j, i, time.Now().Second())

						//_, err := ctx.Send(ctx.IC.ChannelID, fmt.Sprintf("round %d route %d second %v", j, i, time.Now().Second()))
						//if err != nil {
						//	log.Error().Fields(map[string]interface{}{"action": "batch error", "error": err.Error()}).Send()
						//
						//}
					}()
				}
				time.Sleep(time.Second)
				j++
			}
		}()
	}

	return nil
}
