// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: widget_quiz.proto

package widget_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetQuizCallbackType int32

const (
	WidgetQuizCallbackType_WidgetCorrectUser WidgetQuizCallbackType = 0
	WidgetQuizCallbackType_WidgetStop        WidgetQuizCallbackType = 1
	WidgetQuizCallbackType_WidgetGenerate    WidgetQuizCallbackType = 2
)

// Enum value maps for WidgetQuizCallbackType.
var (
	WidgetQuizCallbackType_name = map[int32]string{
		0: "WidgetCorrectUser",
		1: "WidgetStop",
		2: "WidgetGenerate",
	}
	WidgetQuizCallbackType_value = map[string]int32{
		"WidgetCorrectUser": 0,
		"WidgetStop":        1,
		"WidgetGenerate":    2,
	}
)

func (x WidgetQuizCallbackType) Enum() *WidgetQuizCallbackType {
	p := new(WidgetQuizCallbackType)
	*p = x
	return p
}

func (x WidgetQuizCallbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WidgetQuizCallbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_widget_quiz_proto_enumTypes[0].Descriptor()
}

func (WidgetQuizCallbackType) Type() protoreflect.EnumType {
	return &file_widget_quiz_proto_enumTypes[0]
}

func (x WidgetQuizCallbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WidgetQuizCallbackType.Descriptor instead.
func (WidgetQuizCallbackType) EnumDescriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{0}
}

type QuizStatus int32

const (
	QuizStatus_PREPARE QuizStatus = 0
	QuizStatus_PENDING QuizStatus = 1
	QuizStatus_OVER    QuizStatus = 2
)

// Enum value maps for QuizStatus.
var (
	QuizStatus_name = map[int32]string{
		0: "PREPARE",
		1: "PENDING",
		2: "OVER",
	}
	QuizStatus_value = map[string]int32{
		"PREPARE": 0,
		"PENDING": 1,
		"OVER":    2,
	}
)

func (x QuizStatus) Enum() *QuizStatus {
	p := new(QuizStatus)
	*p = x
	return p
}

func (x QuizStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuizStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_widget_quiz_proto_enumTypes[1].Descriptor()
}

func (QuizStatus) Type() protoreflect.EnumType {
	return &file_widget_quiz_proto_enumTypes[1]
}

func (x QuizStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuizStatus.Descriptor instead.
func (QuizStatus) EnumDescriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{1}
}

type UnhandledTxNode int32

const (
	UnhandledTxNode_AddInductees UnhandledTxNode = 0
	UnhandledTxNode_Award        UnhandledTxNode = 1
)

// Enum value maps for UnhandledTxNode.
var (
	UnhandledTxNode_name = map[int32]string{
		0: "AddInductees",
		1: "Award",
	}
	UnhandledTxNode_value = map[string]int32{
		"AddInductees": 0,
		"Award":        1,
	}
)

func (x UnhandledTxNode) Enum() *UnhandledTxNode {
	p := new(UnhandledTxNode)
	*p = x
	return p
}

func (x UnhandledTxNode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnhandledTxNode) Descriptor() protoreflect.EnumDescriptor {
	return file_widget_quiz_proto_enumTypes[2].Descriptor()
}

func (UnhandledTxNode) Type() protoreflect.EnumType {
	return &file_widget_quiz_proto_enumTypes[2]
}

func (x UnhandledTxNode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnhandledTxNode.Descriptor instead.
func (UnhandledTxNode) EnumDescriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{2}
}

type Quiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId     string     `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AppId       string     `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status      QuizStatus `protobuf:"varint,5,opt,name=status,proto3,enum=proto.QuizStatus" json:"status,omitempty"`
	AppType     int32      `protobuf:"varint,6,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	Participate int64      `protobuf:"varint,7,opt,name=participate,proto3" json:"participate,omitempty"`
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Quiz) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Quiz) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Quiz) GetStatus() QuizStatus {
	if x != nil {
		return x.Status
	}
	return QuizStatus_PREPARE
}

func (x *Quiz) GetAppType() int32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

func (x *Quiz) GetParticipate() int64 {
	if x != nil {
		return x.Participate
	}
	return 0
}

type WidgetCreateQuizReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizId  string `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	GroupId string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AppId   string `protobuf:"bytes,3,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppType int32  `protobuf:"varint,4,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
}

func (x *WidgetCreateQuizReq) Reset() {
	*x = WidgetCreateQuizReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetCreateQuizReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetCreateQuizReq) ProtoMessage() {}

func (x *WidgetCreateQuizReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetCreateQuizReq.ProtoReflect.Descriptor instead.
func (*WidgetCreateQuizReq) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{1}
}

func (x *WidgetCreateQuizReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *WidgetCreateQuizReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *WidgetCreateQuizReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WidgetCreateQuizReq) GetAppType() int32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

type WidgetQuizCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizId         string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	OpenId         int64                  `protobuf:"varint,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	GroupId        string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AppId          string                 `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppType        int32                  `protobuf:"varint,7,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	CallbackType   WidgetQuizCallbackType `protobuf:"varint,3,opt,name=callback_type,json=callbackType,proto3,enum=proto.WidgetQuizCallbackType" json:"callback_type,omitempty"`
	ParticipateNum int64                  `protobuf:"varint,6,opt,name=participate_num,json=participateNum,proto3" json:"participate_num,omitempty"`
}

func (x *WidgetQuizCallbackReq) Reset() {
	*x = WidgetQuizCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetQuizCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetQuizCallbackReq) ProtoMessage() {}

func (x *WidgetQuizCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetQuizCallbackReq.ProtoReflect.Descriptor instead.
func (*WidgetQuizCallbackReq) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{2}
}

func (x *WidgetQuizCallbackReq) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *WidgetQuizCallbackReq) GetOpenId() int64 {
	if x != nil {
		return x.OpenId
	}
	return 0
}

func (x *WidgetQuizCallbackReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *WidgetQuizCallbackReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WidgetQuizCallbackReq) GetAppType() int32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

func (x *WidgetQuizCallbackReq) GetCallbackType() WidgetQuizCallbackType {
	if x != nil {
		return x.CallbackType
	}
	return WidgetQuizCallbackType_WidgetCorrectUser
}

func (x *WidgetQuizCallbackReq) GetParticipateNum() int64 {
	if x != nil {
		return x.ParticipateNum
	}
	return 0
}

type GetQuizGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizIds []string `protobuf:"bytes,1,rep,name=quiz_ids,json=quizIds,proto3" json:"quiz_ids,omitempty"`
}

func (x *GetQuizGroupReq) Reset() {
	*x = GetQuizGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuizGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizGroupReq) ProtoMessage() {}

func (x *GetQuizGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizGroupReq.ProtoReflect.Descriptor instead.
func (*GetQuizGroupReq) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{3}
}

func (x *GetQuizGroupReq) GetQuizIds() []string {
	if x != nil {
		return x.QuizIds
	}
	return nil
}

type GetQuizGroupRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizGroup map[string]string `protobuf:"bytes,1,rep,name=quiz_group,json=quizGroup,proto3" json:"quiz_group,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetQuizGroupRespData) Reset() {
	*x = GetQuizGroupRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuizGroupRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizGroupRespData) ProtoMessage() {}

func (x *GetQuizGroupRespData) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizGroupRespData.ProtoReflect.Descriptor instead.
func (*GetQuizGroupRespData) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{4}
}

func (x *GetQuizGroupRespData) GetQuizGroup() map[string]string {
	if x != nil {
		return x.QuizGroup
	}
	return nil
}

type GetQuizGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *WidgetErrorMessage   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *GetQuizGroupRespData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetQuizGroupResp) Reset() {
	*x = GetQuizGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuizGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuizGroupResp) ProtoMessage() {}

func (x *GetQuizGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuizGroupResp.ProtoReflect.Descriptor instead.
func (*GetQuizGroupResp) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{5}
}

func (x *GetQuizGroupResp) GetError() *WidgetErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetQuizGroupResp) GetData() *GetQuizGroupRespData {
	if x != nil {
		return x.Data
	}
	return nil
}

type Inductee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizId  string `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Inductee) Reset() {
	*x = Inductee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Inductee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inductee) ProtoMessage() {}

func (x *Inductee) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inductee.ProtoReflect.Descriptor instead.
func (*Inductee) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{6}
}

func (x *Inductee) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *Inductee) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UnhandledQuiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quiz *Quiz           `protobuf:"bytes,1,opt,name=quiz,proto3" json:"quiz,omitempty"`
	Node UnhandledTxNode `protobuf:"varint,3,opt,name=node,proto3,enum=proto.UnhandledTxNode" json:"node,omitempty"`
}

func (x *UnhandledQuiz) Reset() {
	*x = UnhandledQuiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_quiz_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnhandledQuiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnhandledQuiz) ProtoMessage() {}

func (x *UnhandledQuiz) ProtoReflect() protoreflect.Message {
	mi := &file_widget_quiz_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnhandledQuiz.ProtoReflect.Descriptor instead.
func (*UnhandledQuiz) Descriptor() ([]byte, []int) {
	return file_widget_quiz_proto_rawDescGZIP(), []int{7}
}

func (x *UnhandledQuiz) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

func (x *UnhandledQuiz) GetNode() UnhandledTxNode {
	if x != nil {
		return x.Node
	}
	return UnhandledTxNode_AddInductees
}

var File_widget_quiz_proto protoreflect.FileDescriptor

var file_widget_quiz_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x71, 0x75, 0x69, 0x7a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x77, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0,
	0x01, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74,
	0x65, 0x22, 0x7b, 0x0a, 0x13, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x75, 0x69, 0x7a,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x71, 0x75, 0x69, 0x7a, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0x83,
	0x02, 0x0a, 0x15, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x75, 0x69, 0x7a,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x71, 0x75, 0x69, 0x7a, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x42, 0x0a, 0x0d, 0x63, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x51, 0x75, 0x69,
	0x7a, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x63,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74,
	0x65, 0x4e, 0x75, 0x6d, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x71, 0x75, 0x69, 0x7a, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x71, 0x75, 0x69, 0x7a, 0x49,
	0x64, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x49, 0x0a, 0x0a, 0x71,
	0x75, 0x69, 0x7a, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x51, 0x75, 0x69,
	0x7a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x71, 0x75, 0x69,
	0x7a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x1a, 0x3c, 0x0a, 0x0e, 0x51, 0x75, 0x69, 0x7a, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x74, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3d, 0x0a, 0x08, 0x49, 0x6e,
	0x64, 0x75, 0x63, 0x74, 0x65, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x75, 0x69, 0x7a, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x71, 0x75, 0x69, 0x7a, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5c, 0x0a, 0x0d, 0x55, 0x6e, 0x68,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x1f, 0x0a, 0x04, 0x71, 0x75,
	0x69, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x12, 0x2a, 0x0a, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x54, 0x78, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x2a, 0x53, 0x0a, 0x16, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x51, 0x75, 0x69, 0x7a, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x15, 0x0a, 0x11, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x72, 0x72, 0x65,
	0x63, 0x74, 0x55, 0x73, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x10, 0x02, 0x2a, 0x30, 0x0a, 0x0a,
	0x51, 0x75, 0x69, 0x7a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52,
	0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x56, 0x45, 0x52, 0x10, 0x02, 0x2a, 0x2e,
	0x0a, 0x0f, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x54, 0x78, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x49, 0x6e, 0x64, 0x75, 0x63, 0x74, 0x65, 0x65,
	0x73, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x77, 0x61, 0x72, 0x64, 0x10, 0x01, 0x42, 0x16,
	0x5a, 0x14, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x62, 0x2f, 0x3b, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_widget_quiz_proto_rawDescOnce sync.Once
	file_widget_quiz_proto_rawDescData = file_widget_quiz_proto_rawDesc
)

func file_widget_quiz_proto_rawDescGZIP() []byte {
	file_widget_quiz_proto_rawDescOnce.Do(func() {
		file_widget_quiz_proto_rawDescData = protoimpl.X.CompressGZIP(file_widget_quiz_proto_rawDescData)
	})
	return file_widget_quiz_proto_rawDescData
}

var file_widget_quiz_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_widget_quiz_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_widget_quiz_proto_goTypes = []interface{}{
	(WidgetQuizCallbackType)(0),   // 0: proto.WidgetQuizCallbackType
	(QuizStatus)(0),               // 1: proto.QuizStatus
	(UnhandledTxNode)(0),          // 2: proto.UnhandledTxNode
	(*Quiz)(nil),                  // 3: proto.Quiz
	(*WidgetCreateQuizReq)(nil),   // 4: proto.WidgetCreateQuizReq
	(*WidgetQuizCallbackReq)(nil), // 5: proto.WidgetQuizCallbackReq
	(*GetQuizGroupReq)(nil),       // 6: proto.GetQuizGroupReq
	(*GetQuizGroupRespData)(nil),  // 7: proto.GetQuizGroupRespData
	(*GetQuizGroupResp)(nil),      // 8: proto.GetQuizGroupResp
	(*Inductee)(nil),              // 9: proto.Inductee
	(*UnhandledQuiz)(nil),         // 10: proto.UnhandledQuiz
	nil,                           // 11: proto.GetQuizGroupRespData.QuizGroupEntry
	(*WidgetErrorMessage)(nil),    // 12: proto.WidgetErrorMessage
}
var file_widget_quiz_proto_depIdxs = []int32{
	1,  // 0: proto.Quiz.status:type_name -> proto.QuizStatus
	0,  // 1: proto.WidgetQuizCallbackReq.callback_type:type_name -> proto.WidgetQuizCallbackType
	11, // 2: proto.GetQuizGroupRespData.quiz_group:type_name -> proto.GetQuizGroupRespData.QuizGroupEntry
	12, // 3: proto.GetQuizGroupResp.error:type_name -> proto.WidgetErrorMessage
	7,  // 4: proto.GetQuizGroupResp.data:type_name -> proto.GetQuizGroupRespData
	3,  // 5: proto.UnhandledQuiz.quiz:type_name -> proto.Quiz
	2,  // 6: proto.UnhandledQuiz.node:type_name -> proto.UnhandledTxNode
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_widget_quiz_proto_init() }
func file_widget_quiz_proto_init() {
	if File_widget_quiz_proto != nil {
		return
	}
	file_widget_error_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_widget_quiz_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_quiz_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetCreateQuizReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_quiz_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetQuizCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_quiz_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuizGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_quiz_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuizGroupRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_quiz_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuizGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_quiz_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Inductee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_quiz_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnhandledQuiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_widget_quiz_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_widget_quiz_proto_goTypes,
		DependencyIndexes: file_widget_quiz_proto_depIdxs,
		EnumInfos:         file_widget_quiz_proto_enumTypes,
		MessageInfos:      file_widget_quiz_proto_msgTypes,
	}.Build()
	File_widget_quiz_proto = out.File
	file_widget_quiz_proto_rawDesc = nil
	file_widget_quiz_proto_goTypes = nil
	file_widget_quiz_proto_depIdxs = nil
}
