// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: widget.proto

package widget_pb

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WidgetCommonResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *WidgetErrorMessage `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WidgetCommonResp) Reset() {
	*x = WidgetCommonResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetCommonResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetCommonResp) ProtoMessage() {}

func (x *WidgetCommonResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetCommonResp.ProtoReflect.Descriptor instead.
func (*WidgetCommonResp) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{0}
}

func (x *WidgetCommonResp) GetError() *WidgetErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetAppConfigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
}

func (x *GetAppConfigReq) Reset() {
	*x = GetAppConfigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigReq) ProtoMessage() {}

func (x *GetAppConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigReq.ProtoReflect.Descriptor instead.
func (*GetAppConfigReq) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppConfigReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetAppConfigRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainType       int64             `protobuf:"varint,1,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	ChainId         int64             `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainName       string            `protobuf:"bytes,3,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	ContractAddress map[string]string `protobuf:"bytes,4,rep,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetAppConfigRespData) Reset() {
	*x = GetAppConfigRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppConfigRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigRespData) ProtoMessage() {}

func (x *GetAppConfigRespData) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigRespData.ProtoReflect.Descriptor instead.
func (*GetAppConfigRespData) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{2}
}

func (x *GetAppConfigRespData) GetChainType() int64 {
	if x != nil {
		return x.ChainType
	}
	return 0
}

func (x *GetAppConfigRespData) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetAppConfigRespData) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *GetAppConfigRespData) GetContractAddress() map[string]string {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

type GetAppConfigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *WidgetErrorMessage   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *GetAppConfigRespData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAppConfigResp) Reset() {
	*x = GetAppConfigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppConfigResp) ProtoMessage() {}

func (x *GetAppConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppConfigResp.ProtoReflect.Descriptor instead.
func (*GetAppConfigResp) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{3}
}

func (x *GetAppConfigResp) GetError() *WidgetErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetAppConfigResp) GetData() *GetAppConfigRespData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WidgetGetUsersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AppId   string   `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Address []string `protobuf:"bytes,3,rep,name=address,proto3" json:"address,omitempty"`
	AppType int32    `protobuf:"varint,4,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
}

func (x *WidgetGetUsersReq) Reset() {
	*x = WidgetGetUsersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetGetUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetGetUsersReq) ProtoMessage() {}

func (x *WidgetGetUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetGetUsersReq.ProtoReflect.Descriptor instead.
func (*WidgetGetUsersReq) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{4}
}

func (x *WidgetGetUsersReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *WidgetGetUsersReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WidgetGetUsersReq) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *WidgetGetUsersReq) GetAppType() int32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

type WidgetGetUsersRespData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users map[string]*OpenUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *WidgetGetUsersRespData) Reset() {
	*x = WidgetGetUsersRespData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetGetUsersRespData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetGetUsersRespData) ProtoMessage() {}

func (x *WidgetGetUsersRespData) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetGetUsersRespData.ProtoReflect.Descriptor instead.
func (*WidgetGetUsersRespData) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{5}
}

func (x *WidgetGetUsersRespData) GetUsers() map[string]*OpenUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type OpenUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *OpenUser) Reset() {
	*x = OpenUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenUser) ProtoMessage() {}

func (x *OpenUser) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenUser.ProtoReflect.Descriptor instead.
func (*OpenUser) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{6}
}

func (x *OpenUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WidgetGetUsersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *WidgetErrorMessage     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Data  *WidgetGetUsersRespData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WidgetGetUsersResp) Reset() {
	*x = WidgetGetUsersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WidgetGetUsersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetGetUsersResp) ProtoMessage() {}

func (x *WidgetGetUsersResp) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetGetUsersResp.ProtoReflect.Descriptor instead.
func (*WidgetGetUsersResp) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{7}
}

func (x *WidgetGetUsersResp) GetError() *WidgetErrorMessage {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *WidgetGetUsersResp) GetData() *WidgetGetUsersRespData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReloadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadReq) Reset() {
	*x = ReloadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadReq) ProtoMessage() {}

func (x *ReloadReq) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadReq.ProtoReflect.Descriptor instead.
func (*ReloadReq) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{8}
}

type Contract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChainType int64  `protobuf:"varint,2,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
	ChainId   int64  `protobuf:"varint,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Address   string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Contract) Reset() {
	*x = Contract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{9}
}

func (x *Contract) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contract) GetChainType() int64 {
	if x != nil {
		return x.ChainType
	}
	return 0
}

func (x *Contract) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Contract) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contract) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type Admin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address         string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ContractAddress string `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	SecretKey       string `protobuf:"bytes,4,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
}

func (x *Admin) Reset() {
	*x = Admin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{10}
}

func (x *Admin) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Admin) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Admin) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *Admin) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

type AddressMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OpenId  int64  `protobuf:"varint,2,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
}

func (x *AddressMap) Reset() {
	*x = AddressMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressMap) ProtoMessage() {}

func (x *AddressMap) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressMap.ProtoReflect.Descriptor instead.
func (*AddressMap) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{11}
}

func (x *AddressMap) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AddressMap) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressMap) GetOpenId() int64 {
	if x != nil {
		return x.OpenId
	}
	return 0
}

type AppPreference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId     string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ChainId   int64  `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ChainType int64  `protobuf:"varint,3,opt,name=chain_type,json=chainType,proto3" json:"chain_type,omitempty"`
}

func (x *AppPreference) Reset() {
	*x = AppPreference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPreference) ProtoMessage() {}

func (x *AppPreference) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPreference.ProtoReflect.Descriptor instead.
func (*AppPreference) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{12}
}

func (x *AppPreference) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AppPreference) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *AppPreference) GetChainType() int64 {
	if x != nil {
		return x.ChainType
	}
	return 0
}

type UnhandledTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnhandledQuizTx map[string]*UnhandledQuiz `protobuf:"bytes,1,rep,name=unhandled_quiz_tx,json=unhandledQuizTx,proto3" json:"unhandled_quiz_tx,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *UnhandledTx) Reset() {
	*x = UnhandledTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnhandledTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnhandledTx) ProtoMessage() {}

func (x *UnhandledTx) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnhandledTx.ProtoReflect.Descriptor instead.
func (*UnhandledTx) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{13}
}

func (x *UnhandledTx) GetUnhandledQuizTx() map[string]*UnhandledQuiz {
	if x != nil {
		return x.UnhandledQuizTx
	}
	return nil
}

type Preference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyCode     string `protobuf:"bytes,1,opt,name=key_code,json=keyCode,proto3" json:"key_code,omitempty"`
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	IntValue    int64  `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3" json:"int_value,omitempty"`
}

func (x *Preference) Reset() {
	*x = Preference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_widget_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Preference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preference) ProtoMessage() {}

func (x *Preference) ProtoReflect() protoreflect.Message {
	mi := &file_widget_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preference.ProtoReflect.Descriptor instead.
func (*Preference) Descriptor() ([]byte, []int) {
	return file_widget_proto_rawDescGZIP(), []int{14}
}

func (x *Preference) GetKeyCode() string {
	if x != nil {
		return x.KeyCode
	}
	return ""
}

func (x *Preference) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *Preference) GetIntValue() int64 {
	if x != nil {
		return x.IntValue
	}
	return 0
}

var File_widget_proto protoreflect.FileDescriptor

var file_widget_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x71, 0x75, 0x69, 0x7a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x61,
	0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x77,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x11, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x10, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x28, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x22, 0x90, 0x02, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x5b, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x30, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x1a, 0x42, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x74, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2f, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7a, 0x0a, 0x11,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70,
	0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x61, 0x70, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x61, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x16, 0x57, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x3e, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x1a, 0x49, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x1e,
	0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x78,
	0x0a, 0x12, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0b, 0x0a, 0x09, 0x52, 0x65, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x7b, 0x0a, 0x05, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a,
	0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x4b, 0x65, 0x79, 0x22, 0x53, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x4d, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x0d,
	0x41, 0x70, 0x70, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0xbc,
	0x01, 0x0a, 0x0b, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x54, 0x78, 0x12, 0x53,
	0x0a, 0x11, 0x75, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x5f, 0x71, 0x75, 0x69, 0x7a,
	0x5f, 0x74, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x54, 0x78, 0x2e, 0x55, 0x6e,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x51, 0x75, 0x69, 0x7a, 0x54, 0x78, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0f, 0x75, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x51, 0x75, 0x69,
	0x7a, 0x54, 0x78, 0x1a, 0x58, 0x0a, 0x14, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64,
	0x51, 0x75, 0x69, 0x7a, 0x54, 0x78, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x6e, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x64, 0x51, 0x75,
	0x69, 0x7a, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x67, 0x0a,
	0x0a, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6b,
	0x65, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b,
	0x65, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x74,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xf3, 0x0c, 0x0a, 0x0d, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x12, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x51, 0x75, 0x69,
	0x7a, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x15, 0x2f,
	0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x63, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x3a, 0x01, 0x2a, 0x12, 0x85, 0x01, 0x0a, 0x17, 0x47, 0x61, 0x6d, 0x65,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x79, 0x61, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x42,
	0x61, 0x63, 0x6b, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x79, 0x61, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x6f, 0x79, 0x61, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x26, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x22,
	0x1b, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x72, 0x6f, 0x79,
	0x61, 0x6c, 0x65, 0x2f, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x3a, 0x01, 0x2a, 0x12,
	0x67, 0x0a, 0x10, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51,
	0x75, 0x69, 0x7a, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67,
	0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x71, 0x1a,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18,
	0x22, 0x13, 0x2f, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2f, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x62, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x69, 0x7a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x51, 0x75, 0x69, 0x7a,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1b, 0x22, 0x16, 0x2f, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x2f,
	0x67, 0x65, 0x74, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x3a, 0x01, 0x2a, 0x12, 0x63, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x22, 0x12, 0x2f, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x3a, 0x01,
	0x2a, 0x12, 0x5d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22, 0x11, 0x2f, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x2f, 0x67, 0x65, 0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x3a, 0x01, 0x2a,
	0x12, 0x4e, 0x0a, 0x06, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22, 0x0e, 0x2f,
	0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x72, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x3a, 0x01, 0x2a,
	0x12, 0x6e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1e, 0x22, 0x19, 0x2f, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x74, 0x61, 0x73, 0x6b,
	0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x67, 0x65, 0x74, 0x3a, 0x01, 0x2a,
	0x12, 0x4a, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x7b, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x22, 0x1a, 0x2f, 0x77, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x3a, 0x01, 0x2a, 0x12, 0x72, 0x0a, 0x10, 0x53, 0x61, 0x76,
	0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x22, 0x1a,
	0x2f, 0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x2f, 0x73, 0x61, 0x76, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x58, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x15, 0x2f,
	0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x67, 0x65, 0x74, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x3a, 0x01, 0x2a, 0x12, 0x39, 0x0a, 0x0c, 0x49, 0x6e, 0x69, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x62, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x65, 0x73, 0x12, 0x21, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x69, 0x74, 0x79, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x45, 0x0a,
	0x0e, 0x53, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x55, 0x72, 0x6c, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x57, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x57, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14,
	0x77, 0x69, 0x64, 0x67, 0x65, 0x74, 0x5f, 0x70, 0x62, 0x2f, 0x3b, 0x77, 0x69, 0x64, 0x67, 0x65,
	0x74, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_widget_proto_rawDescOnce sync.Once
	file_widget_proto_rawDescData = file_widget_proto_rawDesc
)

func file_widget_proto_rawDescGZIP() []byte {
	file_widget_proto_rawDescOnce.Do(func() {
		file_widget_proto_rawDescData = protoimpl.X.CompressGZIP(file_widget_proto_rawDescData)
	})
	return file_widget_proto_rawDescData
}

var file_widget_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_widget_proto_goTypes = []interface{}{
	(*WidgetCommonResp)(nil),            // 0: proto.WidgetCommonResp
	(*GetAppConfigReq)(nil),             // 1: proto.GetAppConfigReq
	(*GetAppConfigRespData)(nil),        // 2: proto.GetAppConfigRespData
	(*GetAppConfigResp)(nil),            // 3: proto.GetAppConfigResp
	(*WidgetGetUsersReq)(nil),           // 4: proto.WidgetGetUsersReq
	(*WidgetGetUsersRespData)(nil),      // 5: proto.WidgetGetUsersRespData
	(*OpenUser)(nil),                    // 6: proto.OpenUser
	(*WidgetGetUsersResp)(nil),          // 7: proto.WidgetGetUsersResp
	(*ReloadReq)(nil),                   // 8: proto.ReloadReq
	(*Contract)(nil),                    // 9: proto.Contract
	(*Admin)(nil),                       // 10: proto.Admin
	(*AddressMap)(nil),                  // 11: proto.AddressMap
	(*AppPreference)(nil),               // 12: proto.AppPreference
	(*UnhandledTx)(nil),                 // 13: proto.UnhandledTx
	(*Preference)(nil),                  // 14: proto.Preference
	nil,                                 // 15: proto.GetAppConfigRespData.ContractAddressEntry
	nil,                                 // 16: proto.WidgetGetUsersRespData.UsersEntry
	nil,                                 // 17: proto.UnhandledTx.UnhandledQuizTxEntry
	(*WidgetErrorMessage)(nil),          // 18: proto.WidgetErrorMessage
	(*UnhandledQuiz)(nil),               // 19: proto.UnhandledQuiz
	(*WidgetQuizCallbackReq)(nil),       // 20: proto.WidgetQuizCallbackReq
	(*GameBattleRoyalCallbackReq)(nil),  // 21: proto.GameBattleRoyalCallbackReq
	(*WidgetCreateQuizReq)(nil),         // 22: proto.WidgetCreateQuizReq
	(*GetQuizGroupReq)(nil),             // 23: proto.GetQuizGroupReq
	(*GetTaskTemplateReq)(nil),          // 24: proto.GetTaskTemplateReq
	(*GetTaskActivityReq)(nil),          // 25: proto.GetTaskActivityReq
	(*GetTaskActivityListReq)(nil),      // 26: proto.GetTaskActivityListReq
	(*SaveTaskActivityReq)(nil),         // 27: proto.SaveTaskActivityReq
	(*UserTaskReq)(nil),                 // 28: proto.UserTaskReq
	(*GetActivityParticipatesReq)(nil),  // 29: proto.GetActivityParticipatesReq
	(*UpdateUserTaskReq)(nil),           // 30: proto.UpdateUserTaskReq
	(*SetActivityUrlReq)(nil),           // 31: proto.SetActivityUrlReq
	(*GetActivityWinnerReq)(nil),        // 32: proto.GetActivityWinnerReq
	(*BattleRoyaleCallbackResp)(nil),    // 33: proto.BattleRoyaleCallbackResp
	(*GetQuizGroupResp)(nil),            // 34: proto.GetQuizGroupResp
	(*GetTaskTemplateResp)(nil),         // 35: proto.GetTaskTemplateResp
	(*GetTaskActivityResp)(nil),         // 36: proto.GetTaskActivityResp
	(*GetTaskActivityListResp)(nil),     // 37: proto.GetTaskActivityListResp
	(*SaveTaskActivityResp)(nil),        // 38: proto.SaveTaskActivityResp
	(*UserTaskResp)(nil),                // 39: proto.UserTaskResp
	(*GetActivityParticipatesResp)(nil), // 40: proto.GetActivityParticipatesResp
}
var file_widget_proto_depIdxs = []int32{
	18, // 0: proto.WidgetCommonResp.error:type_name -> proto.WidgetErrorMessage
	15, // 1: proto.GetAppConfigRespData.contract_address:type_name -> proto.GetAppConfigRespData.ContractAddressEntry
	18, // 2: proto.GetAppConfigResp.error:type_name -> proto.WidgetErrorMessage
	2,  // 3: proto.GetAppConfigResp.data:type_name -> proto.GetAppConfigRespData
	16, // 4: proto.WidgetGetUsersRespData.users:type_name -> proto.WidgetGetUsersRespData.UsersEntry
	18, // 5: proto.WidgetGetUsersResp.error:type_name -> proto.WidgetErrorMessage
	5,  // 6: proto.WidgetGetUsersResp.data:type_name -> proto.WidgetGetUsersRespData
	17, // 7: proto.UnhandledTx.unhandled_quiz_tx:type_name -> proto.UnhandledTx.UnhandledQuizTxEntry
	6,  // 8: proto.WidgetGetUsersRespData.UsersEntry.value:type_name -> proto.OpenUser
	19, // 9: proto.UnhandledTx.UnhandledQuizTxEntry.value:type_name -> proto.UnhandledQuiz
	20, // 10: proto.WidgetService.WidgetQuizCallBack:input_type -> proto.WidgetQuizCallbackReq
	21, // 11: proto.WidgetService.GameBattleRoyalCallBack:input_type -> proto.GameBattleRoyalCallbackReq
	22, // 12: proto.WidgetService.WidgetCreateQuiz:input_type -> proto.WidgetCreateQuizReq
	23, // 13: proto.WidgetService.GetQuizGroup:input_type -> proto.GetQuizGroupReq
	1,  // 14: proto.WidgetService.GetAppChainConfig:input_type -> proto.GetAppConfigReq
	4,  // 15: proto.WidgetService.GetUsers:input_type -> proto.WidgetGetUsersReq
	8,  // 16: proto.WidgetService.Reload:input_type -> proto.ReloadReq
	24, // 17: proto.WidgetService.GetTaskTemplate:input_type -> proto.GetTaskTemplateReq
	25, // 18: proto.WidgetService.GetTaskActivity:input_type -> proto.GetTaskActivityReq
	26, // 19: proto.WidgetService.GetTaskActivityList:input_type -> proto.GetTaskActivityListReq
	27, // 20: proto.WidgetService.SaveTaskActivity:input_type -> proto.SaveTaskActivityReq
	28, // 21: proto.WidgetService.GetUserTask:input_type -> proto.UserTaskReq
	28, // 22: proto.WidgetService.InitUserTask:input_type -> proto.UserTaskReq
	29, // 23: proto.WidgetService.GetActivityParticipates:input_type -> proto.GetActivityParticipatesReq
	30, // 24: proto.WidgetService.UpdateUserTask:input_type -> proto.UpdateUserTaskReq
	31, // 25: proto.WidgetService.SetActivityUrl:input_type -> proto.SetActivityUrlReq
	32, // 26: proto.WidgetService.GetActivityWinner:input_type -> proto.GetActivityWinnerReq
	0,  // 27: proto.WidgetService.WidgetQuizCallBack:output_type -> proto.WidgetCommonResp
	33, // 28: proto.WidgetService.GameBattleRoyalCallBack:output_type -> proto.BattleRoyaleCallbackResp
	0,  // 29: proto.WidgetService.WidgetCreateQuiz:output_type -> proto.WidgetCommonResp
	34, // 30: proto.WidgetService.GetQuizGroup:output_type -> proto.GetQuizGroupResp
	3,  // 31: proto.WidgetService.GetAppChainConfig:output_type -> proto.GetAppConfigResp
	7,  // 32: proto.WidgetService.GetUsers:output_type -> proto.WidgetGetUsersResp
	0,  // 33: proto.WidgetService.Reload:output_type -> proto.WidgetCommonResp
	35, // 34: proto.WidgetService.GetTaskTemplate:output_type -> proto.GetTaskTemplateResp
	36, // 35: proto.WidgetService.GetTaskActivity:output_type -> proto.GetTaskActivityResp
	37, // 36: proto.WidgetService.GetTaskActivityList:output_type -> proto.GetTaskActivityListResp
	38, // 37: proto.WidgetService.SaveTaskActivity:output_type -> proto.SaveTaskActivityResp
	39, // 38: proto.WidgetService.GetUserTask:output_type -> proto.UserTaskResp
	39, // 39: proto.WidgetService.InitUserTask:output_type -> proto.UserTaskResp
	40, // 40: proto.WidgetService.GetActivityParticipates:output_type -> proto.GetActivityParticipatesResp
	0,  // 41: proto.WidgetService.UpdateUserTask:output_type -> proto.WidgetCommonResp
	0,  // 42: proto.WidgetService.SetActivityUrl:output_type -> proto.WidgetCommonResp
	40, // 43: proto.WidgetService.GetActivityWinner:output_type -> proto.GetActivityParticipatesResp
	27, // [27:44] is the sub-list for method output_type
	10, // [10:27] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_widget_proto_init() }
func file_widget_proto_init() {
	if File_widget_proto != nil {
		return
	}
	file_widget_quiz_proto_init()
	file_widget_activity_proto_init()
	file_widget_error_proto_init()
	file_widget_game_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_widget_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetCommonResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppConfigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppConfigRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAppConfigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetGetUsersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetGetUsersRespData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WidgetGetUsersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReloadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Admin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppPreference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnhandledTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_widget_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Preference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_widget_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_widget_proto_goTypes,
		DependencyIndexes: file_widget_proto_depIdxs,
		MessageInfos:      file_widget_proto_msgTypes,
	}.Build()
	File_widget_proto = out.File
	file_widget_proto_rawDesc = nil
	file_widget_proto_goTypes = nil
	file_widget_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// WidgetServiceClient is the client API for WidgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WidgetServiceClient interface {
	WidgetQuizCallBack(ctx context.Context, in *WidgetQuizCallbackReq, opts ...grpc.CallOption) (*WidgetCommonResp, error)
	GameBattleRoyalCallBack(ctx context.Context, in *GameBattleRoyalCallbackReq, opts ...grpc.CallOption) (*BattleRoyaleCallbackResp, error)
	WidgetCreateQuiz(ctx context.Context, in *WidgetCreateQuizReq, opts ...grpc.CallOption) (*WidgetCommonResp, error)
	GetQuizGroup(ctx context.Context, in *GetQuizGroupReq, opts ...grpc.CallOption) (*GetQuizGroupResp, error)
	GetAppChainConfig(ctx context.Context, in *GetAppConfigReq, opts ...grpc.CallOption) (*GetAppConfigResp, error)
	GetUsers(ctx context.Context, in *WidgetGetUsersReq, opts ...grpc.CallOption) (*WidgetGetUsersResp, error)
	Reload(ctx context.Context, in *ReloadReq, opts ...grpc.CallOption) (*WidgetCommonResp, error)
	GetTaskTemplate(ctx context.Context, in *GetTaskTemplateReq, opts ...grpc.CallOption) (*GetTaskTemplateResp, error)
	GetTaskActivity(ctx context.Context, in *GetTaskActivityReq, opts ...grpc.CallOption) (*GetTaskActivityResp, error)
	GetTaskActivityList(ctx context.Context, in *GetTaskActivityListReq, opts ...grpc.CallOption) (*GetTaskActivityListResp, error)
	SaveTaskActivity(ctx context.Context, in *SaveTaskActivityReq, opts ...grpc.CallOption) (*SaveTaskActivityResp, error)
	GetUserTask(ctx context.Context, in *UserTaskReq, opts ...grpc.CallOption) (*UserTaskResp, error)
	InitUserTask(ctx context.Context, in *UserTaskReq, opts ...grpc.CallOption) (*UserTaskResp, error)
	GetActivityParticipates(ctx context.Context, in *GetActivityParticipatesReq, opts ...grpc.CallOption) (*GetActivityParticipatesResp, error)
	UpdateUserTask(ctx context.Context, in *UpdateUserTaskReq, opts ...grpc.CallOption) (*WidgetCommonResp, error)
	SetActivityUrl(ctx context.Context, in *SetActivityUrlReq, opts ...grpc.CallOption) (*WidgetCommonResp, error)
	GetActivityWinner(ctx context.Context, in *GetActivityWinnerReq, opts ...grpc.CallOption) (*GetActivityParticipatesResp, error)
}

type widgetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWidgetServiceClient(cc grpc.ClientConnInterface) WidgetServiceClient {
	return &widgetServiceClient{cc}
}

func (c *widgetServiceClient) WidgetQuizCallBack(ctx context.Context, in *WidgetQuizCallbackReq, opts ...grpc.CallOption) (*WidgetCommonResp, error) {
	out := new(WidgetCommonResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/WidgetQuizCallBack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GameBattleRoyalCallBack(ctx context.Context, in *GameBattleRoyalCallbackReq, opts ...grpc.CallOption) (*BattleRoyaleCallbackResp, error) {
	out := new(BattleRoyaleCallbackResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GameBattleRoyalCallBack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) WidgetCreateQuiz(ctx context.Context, in *WidgetCreateQuizReq, opts ...grpc.CallOption) (*WidgetCommonResp, error) {
	out := new(WidgetCommonResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/WidgetCreateQuiz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetQuizGroup(ctx context.Context, in *GetQuizGroupReq, opts ...grpc.CallOption) (*GetQuizGroupResp, error) {
	out := new(GetQuizGroupResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetQuizGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetAppChainConfig(ctx context.Context, in *GetAppConfigReq, opts ...grpc.CallOption) (*GetAppConfigResp, error) {
	out := new(GetAppConfigResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetAppChainConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetUsers(ctx context.Context, in *WidgetGetUsersReq, opts ...grpc.CallOption) (*WidgetGetUsersResp, error) {
	out := new(WidgetGetUsersResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) Reload(ctx context.Context, in *ReloadReq, opts ...grpc.CallOption) (*WidgetCommonResp, error) {
	out := new(WidgetCommonResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/Reload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetTaskTemplate(ctx context.Context, in *GetTaskTemplateReq, opts ...grpc.CallOption) (*GetTaskTemplateResp, error) {
	out := new(GetTaskTemplateResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetTaskTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetTaskActivity(ctx context.Context, in *GetTaskActivityReq, opts ...grpc.CallOption) (*GetTaskActivityResp, error) {
	out := new(GetTaskActivityResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetTaskActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetTaskActivityList(ctx context.Context, in *GetTaskActivityListReq, opts ...grpc.CallOption) (*GetTaskActivityListResp, error) {
	out := new(GetTaskActivityListResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetTaskActivityList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) SaveTaskActivity(ctx context.Context, in *SaveTaskActivityReq, opts ...grpc.CallOption) (*SaveTaskActivityResp, error) {
	out := new(SaveTaskActivityResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/SaveTaskActivity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetUserTask(ctx context.Context, in *UserTaskReq, opts ...grpc.CallOption) (*UserTaskResp, error) {
	out := new(UserTaskResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetUserTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) InitUserTask(ctx context.Context, in *UserTaskReq, opts ...grpc.CallOption) (*UserTaskResp, error) {
	out := new(UserTaskResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/InitUserTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetActivityParticipates(ctx context.Context, in *GetActivityParticipatesReq, opts ...grpc.CallOption) (*GetActivityParticipatesResp, error) {
	out := new(GetActivityParticipatesResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetActivityParticipates", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) UpdateUserTask(ctx context.Context, in *UpdateUserTaskReq, opts ...grpc.CallOption) (*WidgetCommonResp, error) {
	out := new(WidgetCommonResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/UpdateUserTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) SetActivityUrl(ctx context.Context, in *SetActivityUrlReq, opts ...grpc.CallOption) (*WidgetCommonResp, error) {
	out := new(WidgetCommonResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/SetActivityUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetServiceClient) GetActivityWinner(ctx context.Context, in *GetActivityWinnerReq, opts ...grpc.CallOption) (*GetActivityParticipatesResp, error) {
	out := new(GetActivityParticipatesResp)
	err := c.cc.Invoke(ctx, "/proto.WidgetService/GetActivityWinner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WidgetServiceServer is the server API for WidgetService service.
type WidgetServiceServer interface {
	WidgetQuizCallBack(context.Context, *WidgetQuizCallbackReq) (*WidgetCommonResp, error)
	GameBattleRoyalCallBack(context.Context, *GameBattleRoyalCallbackReq) (*BattleRoyaleCallbackResp, error)
	WidgetCreateQuiz(context.Context, *WidgetCreateQuizReq) (*WidgetCommonResp, error)
	GetQuizGroup(context.Context, *GetQuizGroupReq) (*GetQuizGroupResp, error)
	GetAppChainConfig(context.Context, *GetAppConfigReq) (*GetAppConfigResp, error)
	GetUsers(context.Context, *WidgetGetUsersReq) (*WidgetGetUsersResp, error)
	Reload(context.Context, *ReloadReq) (*WidgetCommonResp, error)
	GetTaskTemplate(context.Context, *GetTaskTemplateReq) (*GetTaskTemplateResp, error)
	GetTaskActivity(context.Context, *GetTaskActivityReq) (*GetTaskActivityResp, error)
	GetTaskActivityList(context.Context, *GetTaskActivityListReq) (*GetTaskActivityListResp, error)
	SaveTaskActivity(context.Context, *SaveTaskActivityReq) (*SaveTaskActivityResp, error)
	GetUserTask(context.Context, *UserTaskReq) (*UserTaskResp, error)
	InitUserTask(context.Context, *UserTaskReq) (*UserTaskResp, error)
	GetActivityParticipates(context.Context, *GetActivityParticipatesReq) (*GetActivityParticipatesResp, error)
	UpdateUserTask(context.Context, *UpdateUserTaskReq) (*WidgetCommonResp, error)
	SetActivityUrl(context.Context, *SetActivityUrlReq) (*WidgetCommonResp, error)
	GetActivityWinner(context.Context, *GetActivityWinnerReq) (*GetActivityParticipatesResp, error)
}

// UnimplementedWidgetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWidgetServiceServer struct {
}

func (*UnimplementedWidgetServiceServer) WidgetQuizCallBack(context.Context, *WidgetQuizCallbackReq) (*WidgetCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WidgetQuizCallBack not implemented")
}
func (*UnimplementedWidgetServiceServer) GameBattleRoyalCallBack(context.Context, *GameBattleRoyalCallbackReq) (*BattleRoyaleCallbackResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GameBattleRoyalCallBack not implemented")
}
func (*UnimplementedWidgetServiceServer) WidgetCreateQuiz(context.Context, *WidgetCreateQuizReq) (*WidgetCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WidgetCreateQuiz not implemented")
}
func (*UnimplementedWidgetServiceServer) GetQuizGroup(context.Context, *GetQuizGroupReq) (*GetQuizGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuizGroup not implemented")
}
func (*UnimplementedWidgetServiceServer) GetAppChainConfig(context.Context, *GetAppConfigReq) (*GetAppConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppChainConfig not implemented")
}
func (*UnimplementedWidgetServiceServer) GetUsers(context.Context, *WidgetGetUsersReq) (*WidgetGetUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedWidgetServiceServer) Reload(context.Context, *ReloadReq) (*WidgetCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reload not implemented")
}
func (*UnimplementedWidgetServiceServer) GetTaskTemplate(context.Context, *GetTaskTemplateReq) (*GetTaskTemplateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskTemplate not implemented")
}
func (*UnimplementedWidgetServiceServer) GetTaskActivity(context.Context, *GetTaskActivityReq) (*GetTaskActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskActivity not implemented")
}
func (*UnimplementedWidgetServiceServer) GetTaskActivityList(context.Context, *GetTaskActivityListReq) (*GetTaskActivityListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskActivityList not implemented")
}
func (*UnimplementedWidgetServiceServer) SaveTaskActivity(context.Context, *SaveTaskActivityReq) (*SaveTaskActivityResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTaskActivity not implemented")
}
func (*UnimplementedWidgetServiceServer) GetUserTask(context.Context, *UserTaskReq) (*UserTaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTask not implemented")
}
func (*UnimplementedWidgetServiceServer) InitUserTask(context.Context, *UserTaskReq) (*UserTaskResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitUserTask not implemented")
}
func (*UnimplementedWidgetServiceServer) GetActivityParticipates(context.Context, *GetActivityParticipatesReq) (*GetActivityParticipatesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityParticipates not implemented")
}
func (*UnimplementedWidgetServiceServer) UpdateUserTask(context.Context, *UpdateUserTaskReq) (*WidgetCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserTask not implemented")
}
func (*UnimplementedWidgetServiceServer) SetActivityUrl(context.Context, *SetActivityUrlReq) (*WidgetCommonResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetActivityUrl not implemented")
}
func (*UnimplementedWidgetServiceServer) GetActivityWinner(context.Context, *GetActivityWinnerReq) (*GetActivityParticipatesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivityWinner not implemented")
}

func RegisterWidgetServiceServer(s *grpc.Server, srv WidgetServiceServer) {
	s.RegisterService(&_WidgetService_serviceDesc, srv)
}

func _WidgetService_WidgetQuizCallBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetQuizCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).WidgetQuizCallBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/WidgetQuizCallBack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).WidgetQuizCallBack(ctx, req.(*WidgetQuizCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GameBattleRoyalCallBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameBattleRoyalCallbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GameBattleRoyalCallBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GameBattleRoyalCallBack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GameBattleRoyalCallBack(ctx, req.(*GameBattleRoyalCallbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_WidgetCreateQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetCreateQuizReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).WidgetCreateQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/WidgetCreateQuiz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).WidgetCreateQuiz(ctx, req.(*WidgetCreateQuizReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetQuizGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuizGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetQuizGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetQuizGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetQuizGroup(ctx, req.(*GetQuizGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetAppChainConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetAppChainConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetAppChainConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetAppChainConfig(ctx, req.(*GetAppConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetGetUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetUsers(ctx, req.(*WidgetGetUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/Reload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).Reload(ctx, req.(*ReloadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetTaskTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetTaskTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetTaskTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetTaskTemplate(ctx, req.(*GetTaskTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetTaskActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetTaskActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetTaskActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetTaskActivity(ctx, req.(*GetTaskActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetTaskActivityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskActivityListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetTaskActivityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetTaskActivityList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetTaskActivityList(ctx, req.(*GetTaskActivityListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_SaveTaskActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTaskActivityReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).SaveTaskActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/SaveTaskActivity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).SaveTaskActivity(ctx, req.(*SaveTaskActivityReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetUserTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetUserTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetUserTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetUserTask(ctx, req.(*UserTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_InitUserTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).InitUserTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/InitUserTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).InitUserTask(ctx, req.(*UserTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetActivityParticipates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityParticipatesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetActivityParticipates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetActivityParticipates",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetActivityParticipates(ctx, req.(*GetActivityParticipatesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_UpdateUserTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).UpdateUserTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/UpdateUserTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).UpdateUserTask(ctx, req.(*UpdateUserTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_SetActivityUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActivityUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).SetActivityUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/SetActivityUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).SetActivityUrl(ctx, req.(*SetActivityUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WidgetService_GetActivityWinner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityWinnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetServiceServer).GetActivityWinner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.WidgetService/GetActivityWinner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetServiceServer).GetActivityWinner(ctx, req.(*GetActivityWinnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _WidgetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.WidgetService",
	HandlerType: (*WidgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WidgetQuizCallBack",
			Handler:    _WidgetService_WidgetQuizCallBack_Handler,
		},
		{
			MethodName: "GameBattleRoyalCallBack",
			Handler:    _WidgetService_GameBattleRoyalCallBack_Handler,
		},
		{
			MethodName: "WidgetCreateQuiz",
			Handler:    _WidgetService_WidgetCreateQuiz_Handler,
		},
		{
			MethodName: "GetQuizGroup",
			Handler:    _WidgetService_GetQuizGroup_Handler,
		},
		{
			MethodName: "GetAppChainConfig",
			Handler:    _WidgetService_GetAppChainConfig_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _WidgetService_GetUsers_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _WidgetService_Reload_Handler,
		},
		{
			MethodName: "GetTaskTemplate",
			Handler:    _WidgetService_GetTaskTemplate_Handler,
		},
		{
			MethodName: "GetTaskActivity",
			Handler:    _WidgetService_GetTaskActivity_Handler,
		},
		{
			MethodName: "GetTaskActivityList",
			Handler:    _WidgetService_GetTaskActivityList_Handler,
		},
		{
			MethodName: "SaveTaskActivity",
			Handler:    _WidgetService_SaveTaskActivity_Handler,
		},
		{
			MethodName: "GetUserTask",
			Handler:    _WidgetService_GetUserTask_Handler,
		},
		{
			MethodName: "InitUserTask",
			Handler:    _WidgetService_InitUserTask_Handler,
		},
		{
			MethodName: "GetActivityParticipates",
			Handler:    _WidgetService_GetActivityParticipates_Handler,
		},
		{
			MethodName: "UpdateUserTask",
			Handler:    _WidgetService_UpdateUserTask_Handler,
		},
		{
			MethodName: "SetActivityUrl",
			Handler:    _WidgetService_SetActivityUrl_Handler,
		},
		{
			MethodName: "GetActivityWinner",
			Handler:    _WidgetService_GetActivityWinner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "widget.proto",
}
